apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mypod
  name: mypod
spec:
  ports:
  - name: 80-80
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mypod
  type: NodePort
status:
  loadBalancer: {}
